server:
 port: 8080
 tomcat:
  uri-encoding: UTF-8
  
spring:
 datasource:
  url: jdbc:mysql:docker_mysql_1:3306/DEMO
  username: root
  password: teste
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
   ddl-auto: create-drop
 
 eureka:
  client:
    service-url:
      defaultZone: http://docker_discovery_1:1111/eureka/